[watchman] Add bins for 10.10 and symlink back for 10.11. (#34)
this should repair an issue seen on Stu's 10.11 machine by building a bin on 10.10 and symlinking 10.11 to that vs 10.12.

```
dyld: Symbol not found: _mkostemp
  Referenced from: /Users/stuhood/.cache/pants/bin/watchman/mac/10.11/4.9.0/watchman (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/stuhood/.cache/pants/bin/watchman/mac/10.11/4.9.0/watchman
```